<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\Entity\Webform;
use Drupal\webform\WebformSubmissionForm;

/**
 * Implements hook_form_alter() for webform submission forms.
 */
function student_verification_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
    if ($form_state->getFormObject() instanceof WebformSubmissionForm) {
        $form['#validate'][] = 'student_verification_webform_custom_validate';
    }
}

/**
 * Custom validation callback for the webform.
 */
function student_verification_webform_custom_validate(array &$form, FormStateInterface $form_state)
{
    $build_info = $form_state->getBuildInfo();
    $webform_id = isset($build_info['args'][0]) ? $build_info['args'][0] : NULL;
    // Get the webform ID from the form state
    if (!$webform_id) {
        $webform = $form_state->getFormObject()->getWebform();
        $webform_id = $webform->id();
    }
    $webform_entity = Webform::load($webform_id);

    // $data = $webform_entity->getThirdPartySetting('student_verification', NULL);
    // $webform_entity = Webform::load($webform_id);
    $data = $webform_entity->getThirdPartySettings('student_verification');


    if (isset($data['field_mapping']) && !empty($data['field_mapping'])) {
        foreach ($data['field_mapping'] as $webform_field => $table_field) {
            $table_name = $data['datasource'] ?? NULL;
            $student_verification_data = \Drupal::database()->select($table_name, 's')
                ->fields('s')
                ->execute()
                ->fetchAll();
            $values = $form_state->getValues();

            if (!empty($table_field['db_field']) && !empty($table_field['condition'])) {
                if ($table_field['condition'] == "equals") {
                    $student_verification_data_check = array_filter($student_verification_data, function ($record) use ($webform_field, $table_field, $values) {
                        return $record->{$table_field['db_field']} == ($values[$webform_field] ?? '');
                    });
                } else if ($table_field['condition'] == "not_equals") {
                    $student_verification_data_check = array_filter($student_verification_data, function ($record) use ($webform_field, $table_field, $values) {
                        return $record->{$table_field['db_field']} != ($values[$webform_field] ?? '');
                    });
                }
                if (count($student_verification_data_check) == 0) {
                    $form_state->setErrorByName($webform_field, t('The value entered for @field is not valid.', ['@field' => $webform_field]));
                }
            }
        }
    }
}
