zu_permission_matrix.permission_group.*:
  type: config_entity
  label: 'Permission Group'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Label'
    description:
      type: string
      label: 'Description'
    permissions:
      type: sequence
      label: 'Permissions'
      sequence:
        type: string
        label: 'Permission'
    weight:
      type: integer
      label: 'Weight'

zu_permission_matrix.role_assignments:
  type: config_object
  label: 'Role group assignments'
  mapping:
    assignments:
      type: sequence
      label: 'Assignments'
      sequence:
        type: sequence
        label: 'Group IDs for a role'
        sequence:
          type: string
          label: 'Group ID'
