<?php

namespace Drupal\grapesjs_editor\Form;

use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\File\FileSystemInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\Core\Url;

/**
 * Provides a form to manage email template screenshots.
 */
class TemplateImageManagerForm extends FormBase {

  /**
   * The file system service.
   *
   * @var \Drupal\Core\File\FileSystemInterface
   */
  protected $fileSystem;

  /**
   * Constructs a new TemplateImageManagerForm.
   */
  public function __construct(FileSystemInterface $file_system) {
    $this->fileSystem = $file_system;
  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container) {
    return new static(
      $container->get('file_system')
    );
  }

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    return 'grapesjs_template_image_manager';
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state) {
    $directory = 'public://template_screenshots';
    $files = [];

    if ($this->fileSystem->prepareDirectory($directory)) {
      $all_files = $this->fileSystem->scanDirectory($directory, '/\.png$/');
      
      // Sort files by modification date descending
      usort($all_files, function($a, $b) {
        return filemtime($b->uri) - filemtime($a->uri);
      });

      $total = count($all_files);
      $limit = 12; // 12 images per page
      $pager_manager = \Drupal::service('pager.manager');
      $current_page = $pager_manager->createPager($total, $limit)->getCurrentPage();
      $offset = $current_page * $limit;
      $paged_files = array_slice($all_files, $offset, $limit);

      foreach ($paged_files as $file) {
        $files[] = [
          'uri' => $file->uri,
          'name' => $file->filename,
          'size' => $this->formatBytes(filesize($file->uri)),
          'date' => \Drupal::service('date.formatter')->format(filemtime($file->uri), 'short'),
        ];
      }
    }

    $form['#attached']['library'][] = 'grapesjs_editor/preview';

    $form['help'] = [
      '#markup' => '<p>' . $this->t('Manage screenshots generated by the GrapesJS editor. Only screenshots saved on node save are kept here.') . '</p>',
    ];

    $header = [
      'preview' => $this->t('Preview'),
      'filename' => $this->t('Filename'),
      'size' => $this->t('Size'),
      'date' => $this->t('Modified'),
    ];

    $options = [];
    foreach ($files as $file) {
      $options[$file['uri']] = [
        'preview' => [
          'data' => [
            '#type' => 'html_tag',
            '#tag' => 'img',
            '#attributes' => [
              'src' => \Drupal::service('file_url_generator')->generateAbsoluteString($file['uri']) . '?v=' . filemtime($file['uri']),
              'alt' => $file['name'],
              'width' => 150,
              'style' => 'max-width: 150px; height: auto; border: 1px solid #ccc;',
              'class' => ['screenshot-preview'],
            ],
          ],
        ],
        'filename' => $file['name'],
        'size' => $file['size'],
        'date' => $file['date'],
      ];
    }

    $form['images'] = [
      '#type' => 'tableselect',
      '#header' => $header,
      '#options' => $options,
      '#empty' => $this->t('No screenshots found.'),
    ];

    if (!empty($files)) {
      $form['actions'] = ['#type' => 'actions'];
      $form['actions']['delete'] = [
        '#type' => 'submit',
        '#value' => $this->t('Delete Selected'),
        '#button_type' => 'danger',
      ];
    }

    $form['pager'] = [
      '#type' => 'pager',
    ];

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    $selected = array_filter($form_state->getValue('images'));
    $count = 0;

    foreach ($selected as $uri) {
      try {
        // Try to delete the file.
        $this->fileSystem->delete($uri);
        $count++;
      }
      catch (\Exception $e) {
        $this->messenger()->addError($this->t('Failed to delete @uri: @message', [
          '@uri' => $uri,
          '@message' => $e->getMessage(),
        ]));
      }
    }

    if ($count > 0) {
      $this->messenger()->addStatus($this->t('Deleted @count screenshots.', ['@count' => $count]));
    }
  }

  /**
   * Helper to format bytes.
   */
  protected function formatBytes($bytes) {
    if ($bytes <= 0) {
        return '0 B';
    }
    $units = ['B', 'KB', 'MB', 'GB', 'TB'];
    $pow = floor(log($bytes) / log(1024));
    $pow = min($pow, count($units) - 1);
    $bytes /= pow(1024, $pow);
    return round($bytes, 2) . ' ' . $units[$pow];
  }

}
