zu_rest_api.social_media:
  type: config_object
  label: 'Social Media Settings'
  mapping:
    platforms:
      type: sequence
      label: 'Platforms'
      sequence:
        type: mapping
        label: 'Platform'
        mapping:
          label:
            type: label
            label: 'Label'
          url:
            type: string
            label: 'URL'
          icon:
            type: text
            label: 'SVG Icon'
